/**
 * @fileoverview gRPC-Web generated client stub for pool
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v3.20.3
// source: pool.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');

const proto = {};
proto.pool = require('./pool_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pool.HelloWorldClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.pool.HelloWorldPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.pool.HelloRequest,
 *   !proto.pool.HelloResponse>}
 */
const methodDescriptor_HelloWorld_Hello = new grpc.web.MethodDescriptor(
  '/pool.HelloWorld/Hello',
  grpc.web.MethodType.UNARY,
  proto.pool.HelloRequest,
  proto.pool.HelloResponse,
  /**
   * @param {!proto.pool.HelloRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.pool.HelloResponse.deserializeBinary
);


/**
 * @param {!proto.pool.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.pool.HelloResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.pool.HelloResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.pool.HelloWorldClient.prototype.hello =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/pool.HelloWorld/Hello',
      request,
      metadata || {},
      methodDescriptor_HelloWorld_Hello,
      callback);
};


/**
 * @param {!proto.pool.HelloRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.pool.HelloResponse>}
 *     Promise that resolves to the response
 */
proto.pool.HelloWorldPromiseClient.prototype.hello =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/pool.HelloWorld/Hello',
      request,
      metadata || {},
      methodDescriptor_HelloWorld_Hello);
};


module.exports = proto.pool;

